#!/bin/bash

echo "🚀 BillPay Deployment Automation"
echo "================================"
echo ""

# Build both MCPs
echo "📦 Building MCP servers..."
cd /home/giovanemere/periferia/billpay/mcp-project-analyzer && npm install && npm run build
cd /home/giovanemere/periferia/billpay/mcp-billpay-deploy && npm install && npm run build

echo ""
echo "✅ MCP servers built successfully!"
echo ""
echo "🎯 Available Tools:"
echo ""
echo "📊 Project Analyzer MCP:"
echo "  - clone_repositories: Clone all BillPay repos"
echo "  - analyze_project_structure: Analyze codebase"
echo "  - scan_docker_configs: Find Docker configurations"
echo "  - analyze_ci_cd_pipelines: Review GitHub Actions"
echo "  - identify_aws_requirements: Map AWS services needed"
echo "  - generate_architecture_report: Create comprehensive report"
echo ""
echo "🚀 Deployment MCP:"
echo "  - setup_complete_infrastructure: Full AWS setup"
echo "  - create_ecr_repositories: Container registries"
echo "  - deploy_eks_cluster: Kubernetes cluster"
echo "  - setup_frontend_infrastructure: S3 + CloudFront"
echo "  - deploy_application: Deploy specific apps"
echo "  - generate_terraform_modules: IaC automation"
echo "  - setup_ci_cd_pipelines: GitHub Actions workflows"
echo ""
echo "📋 Recommended Workflow:"
echo "1. Use Project Analyzer to understand current state"
echo "2. Review generated analysis reports"
echo "3. Use Deployment MCP to provision infrastructure"
echo "4. Deploy applications step by step"
echo ""
echo "💡 To use MCPs with Q CLI:"
echo "   Add to your Q CLI configuration:"
echo "   - Analyzer: /home/giovanemere/periferia/billpay/mcp-project-analyzer/dist/index.js"
echo "   - Deployer: /home/giovanemere/periferia/billpay/mcp-billpay-deploy/dist/index.js"
echo ""
echo "🎉 Ready to deploy BillPay to AWS!"
